gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: latest
  replicaCount: 5
  network:
    http:
      servicePort: 8080
      ingress:
        host: demo-test.apps.baloise.dev
